<?php

require_once 'Swat/SwatControl.php';
require_once 'Blorg/Blorg.php';
require_once 'Blorg/BlorgViewFactory.php';

/**
 * Displays a comment with optional buttons to edit, set published status
 * delete and mark as spam
 *
 * @package   Blörg
 * @copyright 2008 silverorange
 * @license   http://www.gnu.org/copyleft/lesser.html LGPL License 2.1
 * @todo      Buttons are only a mockup. They should be generated by JS.
 */
class BlorgCommentDisplay extends SwatControl
{
	// {{{ protected properties

	/**
	 * @var BlorgComment
	 *
	 * @see BlorgCommentDisplay::setComment()
	 */
	protected $comment;

	/**
	 * @var SiteApplication
	 *
	 * @see BlorgCommentDisplay::setApplication()
	 */
	protected $app;

	/**
	 * @var BlorgCommentView
	 *
	 * @see BlorgCommentDisplay::getView()
	 */
	protected static $view;

	// }}}
	// {{{ public function __construct()

	public function __construct($id = null)
	{
		parent::__construct($id);

		$this->addStyleSheet(
			'packages/blorg/admin/styles/blorg-comment-display.css',
			Blorg::PACKAGE_ID);
	}

	// }}}
	// {{{ public function setComment()

	public function setComment(BlorgComment $comment)
	{
		$this->comment = $comment;
	}

	// }}}
	// {{{ public function setApplication()

	public function setApplication(SiteApplication $app)
	{
		$this->app = $app;
	}

	// }}}
	// {{{ public function display()

	public function display()
	{
		if (!$this->visible)
			return;

		if ($this->comment === null)
			return;

		if ($this->app === null)
			return;

		parent::display();

		$container_div = new SwatHtmlTag('div');
		$container_div->class = $this->getCSSClassString();
		$container_div->id = $this->id;
		$container_div->open();

		$this->displayControls();
		$this->displayHeader();

		$view = $this->getView();
		$view->display($this->comment);

		$container_div->close();
	}

	// }}}
	// {{{ protected function displayControls()

	protected function displayControls()
	{
		$unpublish_button = $this->getCompositeWidget('unpublish_button');
		$unpublish_button->sensitive = $this->isSensitive();

		$publish_button = $this->getCompositeWidget('publish_button');
		$publish_button->sensitive = $this->isSensitive();

		$spam_button = $this->getCompositeWidget('spam_button');
		$spam_button->sensitive = $this->isSensitive();

		$delete_button = $this->getCompositeWidget('delete_button');
		$delete_button->sensitive = $this->isSensitive();

		$controls_div = new SwatHtmlTag('div');
		$controls_div->class = 'blorg-comment-display-controls';
		$controls_div->open();

		if ($this->comment->status === BlorgComment::STATUS_PUBLISHED) {
			$publish_button->title = Blorg::_('Unpublish');
		}

		if ($this->comment->spam) {
			$spam_button->title = Blorg::_('Not Spam');
		} else {
			if ($this->comment->status === BlorgComment::STATUS_PENDING) {
				$publish_button->title = Blorg::_('Approve');
				$unpublish_button->title = Blorg::_('Deny');
				$publish_button->display();
				$unpublish_button->display();
			} else {
				$publish_button->display();
			}
		}

		$spam_button->display();
		$delete_button->display();

		$controls_div->close();
	}

	// }}}
	// {{{ protected function displayHeader()

	protected function displayHeader()
	{
		$header_div = new SwatHtmlTag('div');
		$header_div->class = 'blorg-comment-display-header';
		$header_div->open();

		$anchor_tag = new SwatHtmlTag('a');
		$anchor_tag->href = sprintf('Post/Details?id=%s',
			$this->comment->post->id);

		$anchor_tag->setContent($this->comment->post->getTitle());
		echo sprintf(Blorg::_('Comment on %s'), $anchor_tag);

		$this->displayStatusSpan();

		echo ' - ';

		$anchor_tag = new SwatHtmlTag('a');
		$anchor_tag->href = sprintf('Post/CommentEdit?id=%s',
			$this->comment->id);

		$anchor_tag->setContent(Blorg::_('Edit'));
		$anchor_tag->display();

		$header_div->close();
	}

	// }}}
	// {{{ protected function displayStatusSpan()

	protected function displayStatusSpan()
	{
		$status_span = new SwatHtmlTag('span');
		$status_span->id = $this->id.'_status';
		$status_spam->class = 'blorg-comment-display-status';
		$status_span->open();

		if ($this->comment->spam) {
			echo ' - ', Blorg::_('Spam');
		} else {
			switch ($this->comment->status) {
			case BlorgComment::STATUS_UNPUBLISHED:
				echo ' - ', Blorg::_('Unpublished');
				break;

			case BlorgComment::STATUS_PENDING:
				echo ' - ', Blorg::_('Pending');
				break;
			}
		}

		$status_span->close();
	}

	// }}}
	// {{{ protected function getView()

	protected function getView()
	{
		if (self::$view === null && $this->app !== null) {
			self::$view = BlorgViewFactory::get($this->app, 'comment');
			self::$view->setPartMode('bodytext', BlorgView::MODE_SUMMARY);
			self::$view->setPartMode('permalink', BlorgView::MODE_ALL, false);
		}
		return self::$view;
	}

	// }}}
	// {{{ protected function getCSSClassNames()

	/**
	 * Gets the array of CSS classes that are applied to this comment display
	 *
	 * @return array the array of CSS classes that are applied to this comment
	 *                display.
	 */
	protected function getCSSClassNames()
	{
		$classes = array('blorg-comment-display');
		$classes = array_merge($classes, parent::getCSSClassNames());
		$classes[] = $this->getVisibilityCssClassName();
		return $classes;
	}

	// }}}
	// {{{ protected function getVisibilityCssClassName()

	protected function getVisibilityCssClassName()
	{
		if ($this->comment->spam) {
			$class = 'blorg-comment-red';
		} else {
			switch ($this->comment->status) {
			case BlorgComment::STATUS_UNPUBLISHED:
				$class = 'blorg-comment-red';
				break;

			case BlorgComment::STATUS_PENDING:
				$class = 'blorg-comment-yellow';
				break;

			case BlorgComment::STATUS_PUBLISHED:
			default:
				$class = 'blorg-comment-green';
				break;
			}
		}

		return $class;
	}

	// }}}
	// {{{ protected function createCompositeWidgets()

	protected function createCompositeWidgets()
	{
		$unpublish_button = new SwatButton();
		$unpublish_button->id = $this->id.'_unpublish_button';
		$unpublish_button->title = Blorg::_('Unpublish');
		$unpublish_button->classes[] = 'blorg-theme-display-unpublish_button';
		$this->addCompositeWidget($unpublish_button, 'unpublish_button');

		$publish_button = new SwatButton();
		$publish_button->id = $this->id.'_publish_button';
		$publish_button->title = Blorg::_('Publish');
		$publish_button->classes[] = 'blorg-theme-display-publish_button';
		$this->addCompositeWidget($publish_button, 'publish_button');

		$delete_button = new SwatButton();
		$delete_button->id = $this->id.'_delete_button';
		$delete_button->title = Blorg::_('Delete');
		$delete_button->classes[] = 'blorg-theme-display-delete_button';
		$this->addCompositeWidget($delete_button, 'delete_button');

		$spam_button = new SwatButton();
		$spam_button->id = $this->id.'_spam_button';
		$spam_button->title = Blorg::_('Spam');
		$spam_button->classes[] = 'blorg-theme-display-spam_button';
		$this->addCompositeWidget($spam_button, 'spam_button');
	}

	// }}}
}

?>
